Atldev-272
Catrobat/Timesheet pull request #22
Opened 2020-04-03 07:37 UTC by mmeglitsch

Impemented requested changes

2020-04-04 04:40 UTC, m-herold requested changes

2020-04-04 04:40 UTC, m-herold commented on src/main/resources/atlassian-plugin.xml
> -<atlassian-plugin key="${atlassian.plugin.key}" name="${project.name}" plugins-version="2">
Are changes to this file intentional? If not, revert these changes please.

2020-04-04 04:40 UTC, m-herold commented on src/test/java/ut/org/catrobat/jira/timesheet/rest/UserRestTest.java
> +    /*@Test
Please do not comment out these tests. They will be handled in a separate ticket.

2020-04-04 04:40 UTC, m-herold commented on src/test/java/ut/org/catrobat/jira/timesheet/scheduling/ActivityVerificationJobTest.java
> +/*
Please do not comment out these tests. They will be handled in a separate ticket.

2020-04-15 14:33 UTC, closed without merging

2020-04-15 14:33 UTC, mmeglitsch commented
ATLDEV-272 Amended with another pull request